---
- name: deploy server
  hosts: "master"
  become_method: sudo
  gather_facts: yes
  connection: ssh
  
  tasks:
    - name: create namespace
      shell:  kubectl create namespace sock-shop
    - name: apply
      shell: kubectl apply -n sock-shop -f "https://github.com/microservices-demo/microservices-demo/blob/master/deploy/kubernetes/complete-demo.yaml?raw=true"