---
- name: "Test playbook run"
  hosts: all
  tasks:
    - name: "Debug"
      ansible.builtin.debug:
        msg: "Test debug"
    - name: "I am here"
      file:
        path: "/home/yc-user/"
        state: touch