---
- name: Get the token for joining the nodes with Kuberentes master.
  hosts: loclahost
  tasks:
    - name: Get the token for  Kuberentes master.
      shell: kubeadm token create  --print-join-command
      register: kubernetes_join_command
      msg: "{{ kubernetes_join_command.stdout }}"
    - name: Copy join command to local file.
      local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777
