---
- name: "Test playbook run"
  hosts: all
  tasks:
    - name: "Debug"
      ansible.builtin.debug:
        msg: "Test debug"
    - name: "I am here"
      copy:
        dest: "/home/alexey/Downloads"
        content:
            I an here